name: Build and Deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10.2
          otp-version: 22.2
      - name: Install Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile --warnings-as-errors --force
      - name: Cache Deps
        uses: actions/cache@v1
        env:
          cache-name: cache-mix-deps
        with:
          path: deps
          key: ${{ runner.os }}-deps-${{ env.cache-name }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ env.cache-name }}-
            ${{ runner.os }}-deps-
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run Credo
        run: mix credo
      - name: Run Tests
        run: mix test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          repository: mphfish/mphfish.com
          tag_with_ref: true
          build_args: APP_NAME=mphfish,HOSTNAME=localhost,APP_VSN=0.1.0,SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull latest image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: docker pull mphfish/mphfish.com:latest && docker service update --image mphfish/mphfish.com:latest --force mphfish_web
